settings:
  react:
    version: '18.1'
env:
  browser: true
  jest: true
extends:
  - plugin:react/recommended
  - standard
  - prettier
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: latest
  sourceType: module
plugins:
  - react
  - react-hooks
  - '@typescript-eslint'
rules:
  'react/react-in-jsx-scope': 'off'
  '@typescript-eslint/no-unused-vars': 2 # upgrade from default warn
  'react-hooks/rules-of-hooks': 2 # hooks
  'react-hooks/exhaustive-deps': 2 # hooks
  '@typescript-eslint/prefer-interface': 0 # preference
  '@typescript-eslint/array-type': 0 # preference
  '@typescript-eslint/explicit-member-accessibility': 0 # preference (verbosity)
  '@typescript-eslint/no-explicit-any': 0 # preference (conveinence)
  '@typescript-eslint/no-use-before-define': 0 # preference
  '@typescript-eslint/explicit-function-return-type': 0 # preference (verbosity with react, also inference is useful part of TS)
  '@typescript-eslint/explicit-module-boundary-types': 0 # preference (verbosity with react, also inference is useful part of TS)
  '@typescript-eslint/no-var-requires': 0 # used in config files
  '@typescript-eslint/ban-ts-comment': 0 # preference
  '@typescript-eslint/no-empty-function': 0 # preference
  'jsx-a11y/no-onchange': 0 # onBlur as alternative fails react proptype check
  'jsx-a11y/click-events-have-key-events': 0 # preference (not ready for key events)
  'standard/computed-property-even-spacing': 0 # handled by prettier
  'import/no-duplicates': 0
  'react/display-name': 0
  'react/prop-types': 0 # use typescript
  'no-use-before-define': 'off'
