parser: '@typescript-eslint/parser'
settings:
  react:
    version: '18.1'
env:
  browser: true
  jest: true
globals:
  pendo: true
  YodaWidget: true
plugins:
  - react
  - react-hooks
parserOptions:
  ecmaFeatures:
    jsx: true
extends:
  - standard
  - plugin:@typescript-eslint/recommended
  - plugin:jsx-a11y/recommended
  - prettier
  - plugin:mdx/recommended
rules:
  '@typescript-eslint/no-unused-vars': [
    2, 
    { 
      argsIgnorePattern: '^_', 
      varsIgnorePattern: '^_', 
      caughtErrorsIgnorePattern: '^_'
    }
  ] # upgrade from default warn
  '@typescript-eslint/prefer-interface': 0 # preference
  '@typescript-eslint/array-type': 0 # preference
  '@typescript-eslint/explicit-member-accessibility': 0 # preference (verbosity)
  '@typescript-eslint/no-explicit-any': 0 # preference (conveinence)
  '@typescript-eslint/explicit-function-return-type': 0 # preference (verbosity with react, also inference is useful part of TS)
  '@typescript-eslint/explicit-module-boundary-types': 0 # preference (verbosity with react, also inference is useful part of TS)
  '@typescript-eslint/no-parameter-properties': 0 # preference
  '@typescript-eslint/no-empty-function': 0 # preference
  '@typescript-eslint/ban-ts-comment': 0
  'no-use-before-define': 'off'
  'jsx-a11y/click-events-have-key-events': 0 # preference (not ready for key events)
  'jsx-a11y/media-has-caption': 0
  'mdx/no-unused-expressions': 0
  'standard/computed-property-even-spacing': 0
  'react/jsx-uses-react': 1
  'react/jsx-uses-vars': 1
  'react/react-in-jsx-scope': 1
  'react-hooks/rules-of-hooks': 2 # hooks
  'react-hooks/exhaustive-deps': 2 # hooks
  'no-useless-constructor': 0 # not compatible with ts
  'import/no-duplicates': 0 # preference (to allow separate lines for types allowing more readability)
