version: 2.1
orbs:
  aws-s3: circleci/aws-s3@2.0
jobs:
  build:
    docker:
      - image: circleci/node:16.15.0-browsers
    working_directory: ~/repo
    steps:
      - checkout
      - run: yarn install --frozen-lockfile
      - run: yarn lint
      - run: yarn typecheck
      - run: yarn test
      - run: yarn build
      - aws-s3/sync:
          from: build
          to: 's3://farrung.com/'
