version: 2.1
orbs:
  aws-s3: circleci/aws-s3@1.0.11

jobs:
  lint:
    executor: circleci/node:12.9.1-browsers
    working_directory: ~/repo
    steps:
      - checkout
      - run: yarn install --frozen-lockfile
      - run: yarn lint

  test:
    executor: circleci/node:12.9.1-browsers
    working_directory: ~/repo
    steps:
      - checkout
      - run: yarn typecheck
      - run: yarn test

  build:
    executor: circleci/node:12.9.1-browsers
    working_directory: ~/repo
    steps:
      - checkout
      - run: yarn build
      - aws-s3/sync:
          from: build
          to: farrung.com

workflows:
  version: 2.1
  lint_test_build_deploy:
    jobs:
      - lint
      - test:
        requires: -lint
      - build:
          requires:
            - test
          filters:
            branches:
              only: master
