version: 2.1
orbs:
  aws-s3: circleci/aws-s3@1.0.11

jobs:
  lint:
    docker:
      - image: circleci/node:12-browsers
    working_directory: ~/repo
    steps:
      - checkout
      - run: yarn install --frozen-lockfile
      - run: yarn lint

  unit:
    docker:
      - image: circleci/node:12-browsers
    working_directory: ~/repo
    steps:
      - checkout
      - run: yarn typecheck
      - run: yarn test

  build:
    docker:
      - image: circleci/node:12-browsers
    working_directory: ~/repo
    steps:
      - checkout
      - run: yarn build
      - aws-s3/sync:
          from: build
          to: "s3://farrung.com/"

workflows:
  lint_test_build_deploy:
    jobs:
      - lint:
          filters:
            branches:
              only:
                - master
      - unit:
          requires:
            - lint
          filters:
            branches:
              only:
                - master
      - build:
          requires:
            - unit
          filters:
            branches:
              only: master
