version: 2.1
orbs:
  aws-s3: circleci/aws-s3@1.0.11

jobs:
  lint_project:
    docker:
      - image: circleci/node:12-browsers
    working_directory: ~/repo
    steps:
      - checkout
      - run: yarn install --frozen-lockfile
      - run: yarn lint
  unit_test:
    docker:
      - image: circleci/node:12-browsers
    working_directory: ~/repo
    steps:
      - checkout
      - run: yarn typecheck
      - run: yarn test
  build_deploy:
    docker:
      - image: circleci/node:12-browsers
    working_directory: ~/repo
    steps:
      - checkout
      - run: yarn build
      - aws-s3/sync:
          from: build
          to: "s3://farrung.com/"

workflows:
  lint_test_build_deploy:
    jobs:
      - lint_project:
          filters:
            branches:
              only:
                - master
